### ISSUE TITLE
Tried to request object 99 from PICTURE0.XLD, but it only contains 45 items

### ISSUE THREAD

**Issue by neuromancer** [csinkers/ualbion#5]
Using the GOG version of the game results in a crash: 

```
$ ./UAlbion/bin/Release/netcoreapp3.0/linux-x64/UAlbion -vk
at 0: Entered main
at 23: Registered encodings
at 25: Found base directory /home/g/Games/ualbion-fork
at 27: Registering asset manager
at 29: Building AssetLocator
at 37: Start building reflection cache
at 53: Done building reflection cache
at 67: Built AssetLocator
at 69: Attaching ConsoleLogger
at 71: Attached ConsoleLogger
at 71: Attaching Settings
at 72: Attached Settings
at 79: Attaching AssetManager
at 79: Attached AssetManager
at 79: Registered asset manager
at 79: Creating engine
at 86: Attaching ShaderCache
at 86: Attached ShaderCache
at 86: Attaching Engine
at 86: Attaching WindowManager
at 86: Attached WindowManager
at 86: Attached Engine
at 88: Creating main components
at 94: Attaching InputManager
at 94: Attached InputManager
at 95: Attaching LayoutManager
at 95: Attached LayoutManager
at 95: Attaching MapManager
at 95: Attached MapManager
at 95: Attaching PaletteManager
at 259: Attached PaletteManager
at 266: Attaching SceneManager
at 266: Attached SceneManager
at 266: Attaching GameClock
at 266: Attached GameClock
at 267: Attaching SpriteManager
at 267: Attached SpriteManager
at 270: Attaching GameState
at 270: Attached GameState
at 270: Attaching TextManager
at 270: Attached TextManager
at 271: Attaching TextureManager
at 271: Attached TextureManager
at 271: Attaching SlowClock
at 271: Attached SlowClock
at 272: Attaching CursorManager
at 272: Attached CursorManager
at 272: Attaching DebugMapInspector
at 272: Attached DebugMapInspector
at 283: Attaching InputBinder
at 283: Attached InputBinder
at 283: Attaching InputModeStack
at 283: Attached InputModeStack
at 284: Attaching MouseModeStack
at 284: Attached MouseModeStack
at 284: Attaching SceneStack
at 284: Attached SceneStack
at 288: Attaching StatusBar
at 289: Attached StatusBar
at 289: Creating scene-specific components
at 304: Attaching InventoryScreen
at 317: Attaching UiFixedPositionElement`1
at 330: Attached UiFixedPositionElement`1
at 330: Attaching FixedPosition
at 330: Attached FixedPosition
at 330: Attaching FixedPosition
at 330: Attached FixedPosition
at 330: Attaching FixedPosition
at 331: Attaching UiSpriteElement`1
at 331: Attached UiSpriteElement`1
at 331: Attached FixedPosition
at 331: Attached InventoryScreen
at 332: Attaching MainMenu
at 335: Attached MainMenu
at 335: Attaching Sprite`1
at 335: Attached Sprite`1
at 335: Starting new game
at 340: Building event types
at 402: Built event types
set_scene MainMenu
  ExchangeDisabledEvent
  ExchangeDisabledEvent
  ExchangeDisabledEvent
  ExchangeDisabledEvent
at 411: Attaching MenuScene
  set_cursor Cursor
  set_mouse_mode Normal
at 435: Attaching NormalMouseMode
at 435: Attached NormalMouseMode
    set_mouse_mode Normal
  set_input_mode MainMenu
at 436: Attached MenuScene
  ExchangeDisabledEvent
BackendChangedEvent
-- Build SpriteRenderer-- IsDepth0..1: True YInvert: False UV TopLeft: True
-- Build SpriteRenderer-- IsDepth0..1: True YInvert: False UV TopLeft: True
-- Build SpriteRenderer-- IsDepth0..1: True YInvert: False UV TopLeft: True
-- Build SpriteRenderer-- IsDepth0..1: True YInvert: False UV TopLeft: True
-- Build SpriteRenderer-- IsDepth0..1: True YInvert: False UV TopLeft: True
-- Build SpriteRenderer-- IsDepth0..1: True YInvert: False UV TopLeft: True
-- Build SpriteRenderer-- IsDepth0..1: True YInvert: False UV TopLeft: True
-- Build SpriteRenderer-- IsDepth0..1: True YInvert: False UV TopLeft: True
at 750: Running game
at 753: Set up backend
e:window_resized 720 480
at 775: Startup done, rendering first frame
Could not load asset Picture.StatusBar: System.IO.FileNotFoundException: Tried to request object 99 from /run/media/g/ALBION/ALBION/XLDLIBS/PICTURE0.XLD, but it only contains 45 items.
   at UAlbion.Formats.XldFile.GetReaderForObject(Int32 objectIndex, Int32& length) in /home/g/Games/ualbion-fork/Formats/XldFile.cs:line 53
   at UAlbion.Game.Assets.StandardAssetLocator.ReadFromXld(AssetPaths paths, AssetKey key, Func`4 readFunc) in /home/g/Games/ualbion-fork/Game/Assets/StandardAssetLocator.cs:line 176
   at UAlbion.Game.Assets.StandardAssetLocator.LoadAsset(AssetKey key, String name, Func`3 loaderFunc) in /home/g/Games/ualbion-fork/Game/Assets/StandardAssetLocator.cs:line 222
   at UAlbion.Game.Assets.AssetLocator.LoadAssetCached[T](AssetType type, T enumId, GameLanguage language) in /home/g/Games/ualbion-fork/Game/Assets/AssetLocator.cs:line 73
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at UAlbion.Game.Entities.UiSpriteElement`1.UpdateSprite(DrawLayer order) in /home/g/Games/ualbion-fork/Game/Entities/UiSpriteElement.cs:line 64
   at UAlbion.Game.Entities.UiSpriteElement`1.Render(Rectangle extents, Int32 order) in /home/g/Games/ualbion-fork/Game/Entities/UiSpriteElement.cs:line 84
   at UAlbion.Game.Gui.StatusBar.<>c.<Render>b__12_0(IUiElement x, Rectangle y, Int32 z) in /home/g/Games/ualbion-fork/Game/Gui/StatusBar.cs:line 95
   at UAlbion.Game.Gui.StatusBar.DoLayout(Rectangle extents, Int32 order, Func`4 func, Boolean trimOverlap) in /home/g/Games/ualbion-fork/Game/Gui/StatusBar.cs:line 53
   at UAlbion.Game.Gui.StatusBar.Render(Rectangle extents, Int32 order) in /home/g/Games/ualbion-fork/Game/Gui/StatusBar.cs:line 95
   at UAlbion.Game.Gui.LayoutManager.<>c.<Render>b__3_0(Rectangle extents, Int32 order, IUiElement element) in /home/g/Games/ualbion-fork/Game/Gui/LayoutManager.cs:line 87
   at UAlbion.Game.Gui.LayoutManager.DoLayout(Func`4 action) in /home/g/Games/ualbion-fork/Game/Gui/LayoutManager.cs:line 83
   at UAlbion.Game.Gui.LayoutManager.Render() in /home/g/Games/ualbion-fork/Game/Gui/LayoutManager.cs:line 87
   at UAlbion.Game.Gui.LayoutManager.<>c.<.cctor>b__6_0(LayoutManager x, RenderEvent _) in /home/g/Games/ualbion-fork/Game/Gui/LayoutManager.cs:line 18
   at UAlbion.Core.Component.Handler`2.Invoke(Component instance, IEvent event) in /home/g/Games/ualbion-fork/Core/Component.cs:line 26
   at UAlbion.Core.Component.Receive(IEvent event, Object sender) in /home/g/Games/ualbion-fork/Core/Component.cs:line 94
   at UAlbion.Core.Events.EventExchange.Raise(IEvent e, Object sender, Boolean includeParent) in /home/g/Games/ualbion-fork/Core/Events/EventExchange.cs:line 195
   at UAlbion.Core.Scene.RenderAllStages(GraphicsDevice gd, CommandList cl, SceneContext sc, IDictionary`2 renderers) in /home/g/Games/ualbion-fork/Core/Scene.cs:line 49
   at UAlbion.Core.Engine.Draw() in /home/g/Games/ualbion-fork/Core/Engine.cs:line 242
   at UAlbion.Core.Engine.Run() in /home/g/Games/ualbion-fork/Core/Engine.cs:line 166
   at UAlbion.Program.RunGame(EventExchange global, String baseDir) in /home/g/Games/ualbion-fork/UAlbion/Program.cs:line 188
   at UAlbion.Program.Main(String[] args) in /home/g/Games/ualbion-fork/UAlbion/Program.cs:line 92
```

**Comment by csinkers** [comment]
Ah, now I remember, I'd extracted the status bar image from... somewhere and then saved it in data/PICTURE0.XLD/99.bmp in my local environment to be able to load it conveniently. I'll need to go back and see where I pulled it from, whether it was baked into MAIN.EXE somewhere, or possibly just cropped from the bottom of SLAB, and then fix things up to load it directly from the game files.

In any case, the missing image shouldn't be causing a crash, you should just have a once-off non-fatal error message and then the texture will be replaced with a placeholder / broken image texture. I've fixed the bug that was causing the NullReferenceException, so it should at least run now (although you'll have a transparent status bar like in the screenshot Will posted in the other thread)

**Comment by neuromancer** [comment]
It works now, great job!

**Comment by csinkers** [comment]
If you want to get rid of the ugly broken image in the meantime, comment out "Children.AddSprite(_sprite);" (line 32) and the line in DoLayout that calls func(_sprite, ...) (line 53) in Game/StatusBar.cs

**Comment by csinkers** [comment]
FYI: The status bar image is now pulled directly from the SLAB resource, so it should show up for everyone now without having to do any manual conversion.
